numero=int(input("imgrese un numero entero"))
if numero!=0:
    if numero>0:
       if numero%2==0:
          print("el  numero es par positivo")
       else:
        print("numero es impar par positivo ")
    else:
       if numero%2==0:
        print("el numerero es par negativo")
       else:
          print("el numero impar negativo")
else:
   print("el numero es neutro ")       
  

 